services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_URL=http://localhost:8081
      - DOCKER_ENV=true
      - AUTHENTICATION_API_KEY=B6D711FCDE4D4FD5936544120E713976
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - LOG_LEVEL=ERROR  # Mudado de INFO para ERROR para reduzir I/O de disco e CPU durante loops

      # Database
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution@postgres_evolution:5432/evolution
      - DATABASE_CLIENT_NAME=evolution_exchange
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true

      # Redis (Configuração Unificada para Cache e Fila)
      - REDIS_ENABLED=true
      - REDIS_URI=redis://redis_evolution:6379/1
      - REDIS_PREFIX_KEY=evolution
      # Adicione estas linhas para forçar o cache de sessão no Redis (MUITO IMPORTANTE)
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis_evolution:6379/1
      - CACHE_REDIS_PREFIX_KEY=evolution_cache
      - CACHE_LOCAL_ENABLED=false

      # Configurações de Resiliência (EVITA O LOOP DE CPU)
      - WARN_ON_CONNECTION_LOST=false
      - RECONNECT_INTERVAL=5000 # Espera 5s antes de tentar reconectar (Salva CPU)
      - MAX_RECONNECT_RETRIES=5

    volumes:
      - evolution_instances:/evolution/instances

    depends_on:
      - postgres_evolution
      - redis_evolution

  postgres_evolution:
    container_name: postgres_evolution
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
      - POSTGRES_DB=evolution
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  redis_evolution:
    container_name: redis_evolution
    image: redis:7
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - evolution_redis_data:/data

volumes:
  evolution_postgres_data:
  evolution_redis_data:
  evolution_instances:
