version: "3.9"

services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      # Core
      - SERVER_URL=http://localhost:8081
      - DOCKER_ENV=true
      - LOG_LEVEL=ERROR

      # Auth
      - AUTHENTICATION_API_KEY=B6D711FCDE4D4FD5936544120E713976
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true

      # Database
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution@postgres_evolution:5432/evolution
      - DATABASE_CLIENT_NAME=evolution_exchange

      # Redis
      - REDIS_ENABLED=true
      - REDIS_URI=redis://redis_evolution:6379/1
      - REDIS_PREFIX_KEY=evolution

    volumes:
      - evolution_instances:/evolution/instances

    depends_on:
      - postgres_evolution
      - redis_evolution

  postgres_evolution:
    container_name: postgres_evolution
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
    ports:
      - "5433:5432"
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  redis_evolution:
    container_name: redis_evolution
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - evolution_redis_data:/data

volumes:
  evolution_postgres_data:
  evolution_redis_data:
  evolution_instances:
